services:
  pg-db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"

  pg-admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "8080:80"

  ingest-data:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - pg-db
    command: >
      python ingestData.py
      --user ${POSTGRES_USER}
      --password ${POSTGRES_PASSWORD}
      --host pg-db
      --port 5432
      --db ${POSTGRES_DB}
      --tableName green_taxi_data
      --url https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz