version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

# Postgresql database
docker run -it \
  -e POSTGRES_USER="root" \
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \
  -v /workspaces/Rho-DE-Zoomcamp/week1/docker_sql/ny_taxi_postgres_data:/var/lib/postgresql/data \
  -p 5432:5432 \
  --network=pg-network \
  --name pg-db \
  postgres:13
  
# pgAdmin

docker run -it \
  -e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
  -e PGADMIN_DEFAULT_PASSWORD="root" \
  -p 8080:80 \
  --network=pg-network \
  --name pg-admin \
  dpage/pgadmin4

# Ingest data

  python ingestData.py \
    --user="root" \
    --password="root" \
    --host=localhost \
    --port=5432 \
    --db="ny_taxi" \
    --tableName="green_taxi_data" \
    --url="https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz" 


# Ingest data with docker
docker run -it \
    --network=pg-network \
    taxingestdata:v1 \
      --user="root" \
      --password="root" \
      --host=pg-db \
      --port=5432 \
      --db="ny_taxi" \
      --tableName="green_taxi_data" \
      --url="https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-10.csv.gz" 